### ISSUE TITLE
Formal PGDrive v0.1.0 release roadmap

### ISSUE THREAD

**Issue by pengzhenghao** [decisionforce/pgdrive#152]
- [x] 1. Final update of README, with carefully polished languague

- [x] 2. Final update of Documents

- [x] 3. Upload a new expert agent

- [x] 4. Check all test scripts is working (remove failed ones)

- [x] 5. Check all examples scripts is working (three local-run examples, colab script should wait the publication of repo.)

**Comment by pengzhenghao** [comment]
Updated at Dec 26:

* [ ] Finish the env config documentation ( @lqy0057 )
* [ ] Finish the webpage
* [ ] Put a list of links into webpage / readme
* [ ] Sync the examples FROM docs TO readme
* [ ] Sync the first page message (the key features) FROM docs TO readme
* [ ] Upload the new expert agent

**Comment by pengzhenghao** [comment]
Released!
