### ISSUE TITLE
A new traffic system

### ISSUE THREAD

**Issue by lqy0057** [decisionforce/pgdrive#243]
I will implement a new traffic system in **next** version of PGDrive with the following features:
- Based on the dynamic model 
- Based on BulletVehicle() class
- Longitude IDM policy to calculate target speed
- Lateral bicycle policy to determine lane change
- PID control
- Step() with Ego Vehicle When calling doPhysics()
- More efficient!

**Comment by lqy0057** [comment]
**TODO**:
- [ ] The hidden lane in intersection should be added for navigation.
- [ ] The ```BulletContactTest``` should be executed by LaneNode to quickly find neighbor vehicles
- [ ] Find a simple zombie vehicle system
...

**Comment by pengzhenghao** [comment]
Any update on this? Let's formalize this to a plan / project!
